### ISSUE TITLE
data

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [pete-hulson/swo-journal#1]
@pete-hulson would you drop in the output/agesub_ess.csv and totlen_ess.csv files when you get a chance

**Comment by pete-hulson** [comment]
they're showing up on my end, did i not share them correctly?

**Comment by BenWilliams-NOAA** [comment]
only the iss are there 

![image](https://user-images.githubusercontent.com/64659151/228015172-f3ec7f86-da15-47b1-803b-53c8874fb1a6.png)

**Comment by pete-hulson** [comment]
doh, ess not iss... too big to push so trying email
